// Static dataset of 50 properties (fully static, no dynamic logic)

const PROPERTIES = [
  { id: 1, title: "2BHK Flat in Hinjewadi", city: "Pune", area: "Hinjewadi", propertyType: "Flat", size: "2BHK", rent: 35000, amenities: ["Swimming Pool","Lift","Parking"], photos: [], rating: 4.2, reviews: 120, owner: { name: "Owner 1", phone: "9000000001", email: "owner1@gmail.com" }, nearby: ["Hospital","School","Metro Station"] },
  { id: 2, title: "3BHK Villa in Baner", city: "Pune", area: "Baner", propertyType: "Villa", size: "3BHK", rent: 55000, amenities: ["Garden","Parking","Security"], photos: [], rating: 4.6, reviews: 90, owner: { name: "Owner 2", phone: "9000000002", email: "owner2@gmail.com" }, nearby: ["Mall","Hospital"] },
  { id: 3, title: "1BHK Flat in Wakad", city: "Pune", area: "Wakad", propertyType: "Flat", size: "1BHK", rent: 18000, amenities: ["Lift","Security"], photos: [], rating: 3.9, reviews: 60, owner: { name: "Owner 3", phone: "9000000003", email: "owner3@gmail.com" }, nearby: ["School","Mall"] },
  { id: 4, title: "4BHK Penthouse in Kothrud", city: "Pune", area: "Kothrud", propertyType: "Penthouse", size: "4BHK", rent: 85000, amenities: ["Gym","Swimming Pool"], photos: [], rating: 4.8, reviews: 150, owner: { name: "Owner 4", phone: "9000000004", email: "owner4@gmail.com" }, nearby: ["Metro Station","Hospital"] },
  { id: 5, title: "3BHK Bungalow in Hadapsar", city: "Pune", area: "Hadapsar", propertyType: "Bungalow", size: "3BHK", rent: 50000, amenities: ["Garden","Parking"], photos: [], rating: 4.1, reviews: 80, owner: { name: "Owner 5", phone: "9000000005", email: "owner5@gmail.com" }, nearby: ["School","Hospital"] },

  { id: 6, title: "2BHK Flat in Andheri", city: "Mumbai", area: "Andheri", propertyType: "Flat", size: "2BHK", rent: 40000, amenities: ["Lift","Parking"], photos: [], rating: 4.0, reviews: 70, owner: { name: "Owner 6", phone: "9000000006", email: "owner6@gmail.com" }, nearby: ["Airport","Metro Station"] },
  { id: 7, title: "3BHK Villa in Bandra", city: "Mumbai", area: "Bandra", propertyType: "Villa", size: "3BHK", rent: 65000, amenities: ["Garden","Security"], photos: [], rating: 4.5, reviews: 110, owner: { name: "Owner 7", phone: "9000000007", email: "owner7@gmail.com" }, nearby: ["Mall","School"] },
  { id: 8, title: "1BHK Flat in Dadar", city: "Mumbai", area: "Dadar", propertyType: "Flat", size: "1BHK", rent: 22000, amenities: ["Lift"], photos: [], rating: 3.7, reviews: 50, owner: { name: "Owner 8", phone: "9000000008", email: "owner8@gmail.com" }, nearby: ["Railway Station"] },
  { id: 9, title: "4BHK Penthouse in Powai", city: "Mumbai", area: "Powai", propertyType: "Penthouse", size: "4BHK", rent: 95000, amenities: ["Swimming Pool","Gym"], photos: [], rating: 4.9, reviews: 200, owner: { name: "Owner 9", phone: "9000000009", email: "owner9@gmail.com" }, nearby: ["Mall","Airport"] },
  { id: 10, title: "3BHK Bungalow in Borivali", city: "Mumbai", area: "Borivali", propertyType: "Bungalow", size: "3BHK", rent: 60000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: 95, owner: { name: "Owner 10", phone: "9000000010", email: "owner10@gmail.com" }, nearby: ["School","Hospital"] },

  { id: 11, title: "2BHK Flat in Nashik Road", city: "Nashik", area: "Nashik Road", propertyType: "Flat", size: "2BHK", rent: 28000, amenities: ["Lift","Parking"], photos: [], rating: 4.0, reviews: 65, owner: { name: "Owner 11", phone: "9000000011", email: "owner11@gmail.com" }, nearby: ["Railway Station","School"] },
  { id: 12, title: "3BHK Villa in Gangapur", city: "Nashik", area: "Gangapur", propertyType: "Villa", size: "3BHK", rent: 48000, amenities: ["Garden","Security"], photos: [], rating: 4.3, reviews: 78, owner: { name: "Owner 12", phone: "9000000012", email: "owner12@gmail.com" }, nearby: ["Hospital","Mall"] },
  { id: 13, title: "1BHK Flat in Panchavati", city: "Nashik", area: "Panchavati", propertyType: "Flat", size: "1BHK", rent: 16000, amenities: ["Lift"], photos: [], rating: 3.8, reviews: 40, owner: { name: "Owner 13", phone: "9000000013", email: "owner13@gmail.com" }, nearby: ["Temple","School"] },
  { id: 14, title: "4BHK Penthouse in Indira Nagar", city: "Nashik", area: "Indira Nagar", propertyType: "Penthouse", size: "4BHK", rent: 75000, amenities: ["Gym","Swimming Pool"], photos: [], rating: 4.7, reviews: 140, owner: { name: "Owner 14", phone: "9000000014", email: "owner14@gmail.com" }, nearby: ["Mall","Hospital"] },
  { id: 15, title: "3BHK Bungalow in College Road", city: "Nashik", area: "College Road", propertyType: "Bungalow", size: "3BHK", rent: 45000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: 85, owner: { name: "Owner 15", phone: "9000000015", email: "owner15@gmail.com" }, nearby: ["School","Hospital"] },

  // Continue similar variation till 50

  { id: 16, title: "2BHK Flat in Dharampeth", city: "Nagpur", area: "Dharampeth", propertyType: "Flat", size: "2BHK", rent: 30000, amenities: ["Lift","Parking"], photos: [], rating: 4.1, reviews: 75, owner: { name: "Owner 16", phone: "9000000016", email: "owner16@gmail.com" }, nearby: ["Hospital","School"] },
  { id: 17, title: "3BHK Villa in Wardha Road", city: "Nagpur", area: "Wardha Road", propertyType: "Villa", size: "3BHK", rent: 52000, amenities: ["Garden","Security"], photos: [], rating: 4.4, reviews: 92, owner: { name: "Owner 17", phone: "9000000017", email: "owner17@gmail.com" }, nearby: ["Airport","Mall"] },
  { id: 18, title: "1BHK Flat in Sitabuldi", city: "Nagpur", area: "Sitabuldi", propertyType: "Flat", size: "1BHK", rent: 17000, amenities: ["Lift"], photos: [], rating: 3.9, reviews: 55, owner: { name: "Owner 18", phone: "9000000018", email: "owner18@gmail.com" }, nearby: ["Metro Station"] },
  { id: 19, title: "4BHK Penthouse in Pratap Nagar", city: "Nagpur", area: "Pratap Nagar", propertyType: "Penthouse", size: "4BHK", rent: 80000, amenities: ["Swimming Pool","Gym"], photos: [], rating: 4.8, reviews: 160, owner: { name: "Owner 19", phone: "9000000019", email: "owner19@gmail.com" }, nearby: ["Mall","Hospital"] },
  { id: 20, title: "3BHK Bungalow in Manish Nagar", city: "Nagpur", area: "Manish Nagar", propertyType: "Bungalow", size: "3BHK", rent: 47000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: 88, owner: { name: "Owner 20", phone: "9000000020", email: "owner20@gmail.com" }, nearby: ["School","Hospital"] },

  // Final set for Aurangabad

  { id: 21, title: "2BHK Flat in CIDCO", city: "Aurangabad", area: "CIDCO", propertyType: "Flat", size: "2BHK", rent: 26000, amenities: ["Lift","Parking"], photos: [], rating: 4.0, reviews: 60, owner: { name: "Owner 21", phone: "9000000021", email: "owner21@gmail.com" }, nearby: ["School","Hospital"] },
  { id: 22, title: "3BHK Villa in Garkheda", city: "Aurangabad", area: "Garkheda", propertyType: "Villa", size: "3BHK", rent: 46000, amenities: ["Garden","Security"], photos: [], rating: 4.3, reviews: 85, owner: { name: "Owner 22", phone: "9000000022", email: "owner22@gmail.com" }, nearby: ["Mall","School"] },
  { id: 23, title: "1BHK Flat in Osmanpura", city: "Aurangabad", area: "Osmanpura", propertyType: "Flat", size: "1BHK", rent: 15000, amenities: ["Lift"], photos: [], rating: 3.7, reviews: 40, owner: { name: "Owner 23", phone: "9000000023", email: "owner23@gmail.com" }, nearby: ["Hospital"] },
  { id: 24, title: "4BHK Penthouse in Jalna Road", city: "Aurangabad", area: "Jalna Road", propertyType: "Penthouse", size: "4BHK", rent: 70000, amenities: ["Swimming Pool","Gym"], photos: [], rating: 4.7, reviews: 130, owner: { name: "Owner 24", phone: "9000000024", email: "owner24@gmail.com" }, nearby: ["Mall","Airport"] },
  { id: 25, title: "3BHK Bungalow in Satara", city: "Aurangabad", area: "Satara", propertyType: "Bungalow", size: "3BHK", rent: 42000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: 90, owner: { name: "Owner 25", phone: "9000000025", email: "owner25@gmail.com" }, nearby: ["School","Hospital"] },

  // Pune - Additional properties
  { id: 26, title: "2BHK Flat in Viman Nagar", city: "Pune", area: "Viman Nagar", propertyType: "Flat", size: "2BHK", rent: 38000, amenities: ["Lift","Parking","Gym"], photos: [], rating: 4.3, reviews: 110, owner: { name: "Owner 26", phone: "9000000026", email: "owner26@gmail.com" }, nearby: ["Airport","School"] },
  { id: 27, title: "3BHK Villa in Kalyani Nagar", city: "Pune", area: "Kalyani Nagar", propertyType: "Villa", size: "3BHK", rent: 58000, amenities: ["Garden","Parking","Security"], photos: [], rating: 4.5, reviews: 100, owner: { name: "Owner 27", phone: "9000000027", email: "owner27@gmail.com" }, nearby: ["Restaurant","Hospital"] },
  { id: 28, title: "1BHK Flat in Shivajinagar", city: "Pune", area: "Shivajinagar", propertyType: "Flat", size: "1BHK", rent: 19000, amenities: ["Lift","Security"], photos: [], rating: 3.8, reviews: 65, owner: { name: "Owner 28", phone: "9000000028", email: "owner28@gmail.com" }, nearby: ["Market","School"] },
  { id: 29, title: "4BHK Penthouse in Baner", city: "Pune", area: "Baner", propertyType: "Penthouse", size: "4BHK", rent: 88000, amenities: ["Swimming Pool","Gym","Garden"], photos: [], rating: 4.9, reviews: 170, owner: { name: "Owner 29", phone: "9000000029", email: "owner29@gmail.com" }, nearby: ["Mall","Hospital"] },
  { id: 30, title: "3BHK Bungalow in Pimple Saudagar", city: "Pune", area: "Pimple Saudagar", propertyType: "Bungalow", size: "3BHK", rent: 52000, amenities: ["Garden","Parking","Lift"], photos: [], rating: 4.2, reviews: 92, owner: { name: "Owner 30", phone: "9000000030", email: "owner30@gmail.com" }, nearby: ["School","Mall"] },

  // Mumbai - Additional properties
  { id: 31, title: "2BHK Flat in Worli", city: "Mumbai", area: "Worli", propertyType: "Flat", size: "2BHK", rent: 45000, amenities: ["Lift","Parking","Gym"], photos: [], rating: 4.4, reviews: 125, owner: { name: "Owner 31", phone: "9000000031", email: "owner31@gmail.com" }, nearby: ["Sea Face","Mall"] },
  { id: 32, title: "3BHK Villa in Juhu", city: "Mumbai", area: "Juhu", propertyType: "Villa", size: "3BHK", rent: 70000, amenities: ["Garden","Security","Swimming Pool"], photos: [], rating: 4.6, reviews: 115, owner: { name: "Owner 32", phone: "9000000032", email: "owner32@gmail.com" }, nearby: ["Beach","Restaurant"] },
  { id: 33, title: "1BHK Flat in Thane", city: "Mumbai", area: "Thane", propertyType: "Flat", size: "1BHK", rent: 20000, amenities: ["Lift","Security"], photos: [], rating: 3.9, reviews: 70, owner: { name: "Owner 33", phone: "9000000033", email: "owner33@gmail.com" }, nearby: ["Lake","School"] },
  { id: 34, title: "4BHK Penthouse in Mumbai Central", city: "Mumbai", area: "Mumbai Central", propertyType: "Penthouse", size: "4BHK", rent: 100000, amenities: ["Swimming Pool","Gym","Spa"], photos: [], rating: 4.8, reviews: 180, owner: { name: "Owner 34", phone: "9000000034", email: "owner34@gmail.com" }, nearby: ["Downtown","Airport"] },
  { id: 35, title: "3BHK Bungalow in Navi Mumbai", city: "Mumbai", area: "Navi Mumbai", propertyType: "Bungalow", size: "3BHK", rent: 55000, amenities: ["Garden","Parking","Lift"], photos: [], rating: 4.3, reviews: 98, owner: { name: "Owner 35", phone: "9000000035", email: "owner35@gmail.com" }, nearby: ["Metro Station","School"] },

  // Nashik - Additional properties
  { id: 36, title: "2BHK Flat in Satpur", city: "Nashik", area: "Satpur", propertyType: "Flat", size: "2BHK", rent: 27000, amenities: ["Lift","Parking"], photos: [], rating: 4.1, reviews: 68, owner: { name: "Owner 36", phone: "9000000036", email: "owner36@gmail.com" }, nearby: ["School","Hospital"] },
  { id: 37, title: "3BHK Villa in Manmad", city: "Nashik", area: "Manmad", propertyType: "Villa", size: "3BHK", rent: 50000, amenities: ["Garden","Security"], photos: [], rating: 4.4, reviews: 82, owner: { name: "Owner 37", phone: "9000000037", email: "owner37@gmail.com" }, nearby: ["Railway Station","Mall"] },
  { id: 38, title: "1BHK Flat in Deolali", city: "Nashik", area: "Deolali", propertyType: "Flat", size: "1BHK", rent: 15500, amenities: ["Lift"], photos: [], rating: 3.7, reviews: 45, owner: { name: "Owner 38", phone: "9000000038", email: "owner38@gmail.com" }, nearby: ["Cantonment","School"] },
  { id: 39, title: "4BHK Penthouse in Nashik Central", city: "Nashik", area: "Nashik Central", propertyType: "Penthouse", size: "4BHK", rent: 78000, amenities: ["Gym","Swimming Pool","Garden"], photos: [], rating: 4.7, reviews: 145, owner: { name: "Owner 39", phone: "9000000039", email: "owner39@gmail.com" }, nearby: ["Market","Hospital"] },
  { id: 40, title: "3BHK Bungalow in Umanabad", city: "Nashik", area: "Umanabad", propertyType: "Bungalow", size: "3BHK", rent: 48000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: 87, owner: { name: "Owner 40", phone: "9000000040", email: "owner40@gmail.com" }, nearby: ["School","Hospital"] },

  // Nagpur - Additional properties
  { id: 41, title: "2BHK Flat in Ramdaspeth", city: "Nagpur", area: "Ramdaspeth", propertyType: "Flat", size: "2BHK", rent: 31000, amenities: ["Lift","Parking","Gym"], photos: [], rating: 4.2, reviews: 78, owner: { name: "Owner 41", phone: "9000000041", email: "owner41@gmail.com" }, nearby: ["Market","School"] },
  { id: 42, title: "3BHK Villa in Nagpur North", city: "Nagpur", area: "Nagpur North", propertyType: "Villa", size: "3BHK", rent: 54000, amenities: ["Garden","Security","Lift"], photos: [], rating: 4.5, reviews: 95, owner: { name: "Owner 42", phone: "9000000042", email: "owner42@gmail.com" }, nearby: ["Golf Course","Hospital"] },
  { id: 43, title: "1BHK Flat in Itwari", city: "Nagpur", area: "Itwari", propertyType: "Flat", size: "1BHK", rent: 18000, amenities: ["Lift","Security"], photos: [], rating: 3.8, reviews: 60, owner: { name: "Owner 43", phone: "9000000043", email: "owner43@gmail.com" }, nearby: ["School","Mall"] },
  { id: 44, title: "4BHK Penthouse in South Nagpur", city: "Nagpur", area: "South Nagpur", propertyType: "Penthouse", size: "4BHK", rent: 82000, amenities: ["Swimming Pool","Gym","Spa"], photos: [], rating: 4.8, reviews: 165, owner: { name: "Owner 44", phone: "9000000044", email: "owner44@gmail.com" }, nearby: ["Race Course","Restaurant"] },
  { id: 45, title: "3BHK Bungalow in Ameerpeth", city: "Nagpur", area: "Ameerpeth", propertyType: "Bungalow", size: "3BHK", rent: 49000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: 90, owner: { name: "Owner 45", phone: "9000000045", email: "owner45@gmail.com" }, nearby: ["School","Hospital"] },

  // Aurangabad - Additional properties
  { id: 46, title: "2BHK Flat in Aurangabad East", city: "Aurangabad", area: "Aurangabad East", propertyType: "Flat", size: "2BHK", rent: 27000, amenities: ["Lift","Parking"], photos: [], rating: 4.1, reviews: 63, owner: { name: "Owner 46", phone: "9000000046", email: "owner46@gmail.com" }, nearby: ["Bibi Ka Maqbara","School"] },
  { id: 47, title: "3BHK Villa in Paithan Gate", city: "Aurangabad", area: "Paithan Gate", propertyType: "Villa", size: "3BHK", rent: 47000, amenities: ["Garden","Security"], photos: [], rating: 4.3, reviews: 88, owner: { name: "Owner 47", phone: "9000000047", email: "owner47@gmail.com" }, nearby: ["Temple","Hospital"] },
  { id: 48, title: "1BHK Flat in Chikhalwadi", city: "Aurangabad", area: "Chikhalwadi", propertyType: "Flat", size: "1BHK", rent: 16000, amenities: ["Lift"], photos: [], rating: 3.8, reviews: 42, owner: { name: "Owner 48", phone: "9000000048", email: "owner48@gmail.com" }, nearby: ["School"] },
  { id: 49, title: "4BHK Penthouse in Aurangabad West", city: "Aurangabad", area: "Aurangabad West", propertyType: "Penthouse", size: "4BHK", rent: 72000, amenities: ["Swimming Pool","Gym"], photos: [], rating: 4.7, reviews: 135, owner: { name: "Owner 49", phone: "9000000049", email: "owner49@gmail.com" }, nearby: ["Mall","Hospital"] },
  { id: 50, title: "3BHK Bungalow in Railway Station Road", city: "Aurangabad", area: "Railway Station Road", propertyType: "Bungalow", size: "3BHK", rent: 44000, amenities: ["Garden","Parking","Security"], photos: [], rating: 4.2, reviews: 92, owner: { name: "Owner 50", phone: "9000000050", email: "owner50@gmail.com" }, nearby: ["Railway Station","School"] }

  
];

export default PROPERTIES;
