// Static dataset of 50 properties (fully static, no dynamic logic)

const PROPERTIES = [
  { id: 1, title: "2BHK Flat in Hinjewadi", city: "Pune", area: "Hinjewadi", propertyType: "Flat", size: "2BHK", furnished: "semifurnished", rent: 35000, amenities: ["Swimming Pool","Lift","Parking"], photos: [], rating: 4.2, reviews: [{ reviewer: "Rajesh Kumar", comment: "Great property, excellent management", rating: 4.5 }, { reviewer: "Priya Singh", comment: "Perfect location, friendly landlord", rating: 4 }, { reviewer: "Amit Patel", comment: "Good amenities, well maintained", rating: 4.2 }], owner: { name: "Owner 1", phone: "9000000001", email: "owner1@gmail.com" }, nearby: ["Hospital","School","Metro Station"] },
  { id: 2, title: "3BHK Villa in Baner", city: "Pune", area: "Baner", propertyType: "Villa", size: "3BHK", furnished: "furnished", rent: 55000, amenities: ["Garden","Parking","Security"], photos: [], rating: 4.6, reviews: [{ reviewer: "Neha Gupta", comment: "Beautiful villa with spacious garden", rating: 4.7 }, { reviewer: "Vikram Sharma", comment: "Excellent security and parking", rating: 4.6 }, { reviewer: "Divya Nair", comment: "Perfect for family, great neighborhood", rating: 4.5 }], owner: { name: "Owner 2", phone: "9000000002", email: "owner2@gmail.com" }, nearby: ["Mall","Hospital"] },
  { id: 3, title: "1BHK Flat in Wakad", city: "Pune", area: "Wakad", propertyType: "Flat", size: "1BHK", furnished: "unfurnished", rent: 18000, amenities: ["Lift","Security"], photos: [], rating: 3.9, reviews: [{ reviewer: "Rohan Das", comment: "Compact but comfortable", rating: 3.8 }, { reviewer: "Sneha Reddy", comment: "Good location, reasonable price", rating: 4 }, { reviewer: "Arjun Singh", comment: "Basic amenities, could be better", rating: 3.9 }], owner: { name: "Owner 3", phone: "9000000003", email: "owner3@gmail.com" }, nearby: ["School","Mall"] },
  { id: 4, title: "4BHK Penthouse in Kothrud", city: "Pune", area: "Kothrud", propertyType: "Penthouse", size: "4BHK", furnished: "furnished", rent: 85000, amenities: ["Gym","Swimming Pool"], photos: [], rating: 4.8, reviews: [{ reviewer: "Sanjay Verma", comment: "Luxurious penthouse with best view", rating: 4.9 }, { reviewer: "Anjali Desai", comment: "Amazing amenities and maintenance", rating: 4.8 }, { reviewer: "Ravi Chopra", comment: "Perfect for premium living", rating: 4.7 }], owner: { name: "Owner 4", phone: "9000000004", email: "owner4@gmail.com" }, nearby: ["Metro Station","Hospital"] },
  { id: 5, title: "3BHK Bungalow in Hadapsar", city: "Pune", area: "Hadapsar", propertyType: "Bungalow", size: "3BHK", furnished: "semifurnished", rent: 50000, amenities: ["Garden","Parking"], photos: [], rating: 4.1, reviews: [{ reviewer: "Tara Joshi", comment: "Beautiful bungalow with great garden", rating: 4.2 }, { reviewer: "Nikhil Sharma", comment: "Good property, responsive owner", rating: 4.1 }, { reviewer: "Meera Iyer", comment: "Peaceful location, family friendly", rating: 4 }], owner: { name: "Owner 5", phone: "9000000005", email: "owner5@gmail.com" }, nearby: ["School","Hospital"] },

  { id: 6, title: "2BHK Flat in Andheri", city: "Mumbai", area: "Andheri", propertyType: "Flat", size: "2BHK", furnished: "furnished", rent: 40000, amenities: ["Lift","Parking"], photos: [], rating: 4.0, reviews: [{ reviewer: "Akshay Thakur", comment: "Good flat near airport, convenient", rating: 4.1 }, { reviewer: "Zara Khan", comment: "Decent property, could use more amenities", rating: 3.9 }, { reviewer: "Karan Bhat", comment: "Fair price for location", rating: 4 }], owner: { name: "Owner 6", phone: "9000000006", email: "owner6@gmail.com" }, nearby: ["Airport","Metro Station"] },
  { id: 7, title: "3BHK Villa in Bandra", city: "Mumbai", area: "Bandra", propertyType: "Villa", size: "3BHK", furnished: "semifurnished", rent: 65000, amenities: ["Garden","Security"], photos: [], rating: 4.5, reviews: [{ reviewer: "Rucha Deshmukh", comment: "Elegant villa in prime location", rating: 4.6 }, { reviewer: "Aman Malhotra", comment: "Excellent security features", rating: 4.5 }, { reviewer: "Pooja Singh", comment: "Great for young professionals", rating: 4.4 }], owner: { name: "Owner 7", phone: "9000000007", email: "owner7@gmail.com" }, nearby: ["Mall","School"] },
  { id: 8, title: "1BHK Flat in Dadar", city: "Mumbai", area: "Dadar", propertyType: "Flat", size: "1BHK", furnished: "unfurnished", rent: 22000, amenities: ["Lift"], photos: [], rating: 3.7, reviews: [{ reviewer: "Rohit Nair", comment: "Small but well-located", rating: 3.8 }, { reviewer: "Isha Kapoor", comment: "Average property, basic facilities", rating: 3.6 }, { reviewer: "Dev Patel", comment: "Good for singles, needs upgrades", rating: 3.7 }], owner: { name: "Owner 8", phone: "9000000008", email: "owner8@gmail.com" }, nearby: ["Railway Station"] },
  { id: 9, title: "4BHK Penthouse in Powai", city: "Mumbai", area: "Powai", propertyType: "Penthouse", size: "4BHK", furnished: "furnished", rent: 95000, amenities: ["Swimming Pool","Gym"], photos: [], rating: 4.9, reviews: [{ reviewer: "Suhail Ansari", comment: "Premium penthouse, exceptional service", rating: 5 }, { reviewer: "Natasha Sharma", comment: "Luxury living at its best", rating: 4.9 }, { reviewer: "Vivek Gupta", comment: "Outstanding property and amenities", rating: 4.8 }], owner: { name: "Owner 9", phone: "9000000009", email: "owner9@gmail.com" }, nearby: ["Mall","Airport"] },
  { id: 10, title: "3BHK Bungalow in Borivali", city: "Mumbai", area: "Borivali", propertyType: "Bungalow", size: "3BHK", furnished: "semifurnished", rent: 60000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: [{ reviewer: "Lily Fernandes", comment: "Spacious bungalow, great garden", rating: 4.3 }, { reviewer: "Marco D'Silva", comment: "Family-friendly neighborhood", rating: 4.2 }, { reviewer: "Sheila Desai", comment: "Good property, responsive management", rating: 4.1 }], owner: { name: "Owner 10", phone: "9000000010", email: "owner10@gmail.com" }, nearby: ["School","Hospital"] },

  { id: 11, title: "2BHK Flat in Nashik Road", city: "Nashik", area: "Nashik Road", propertyType: "Flat", size: "2BHK", furnished: "unfurnished", rent: 28000, amenities: ["Lift","Parking"], photos: [], rating: 4.0, reviews: [{ reviewer: "Suresh Rao", comment: "Good locality, fair prices", rating: 4 }, { reviewer: "Vaishali Jadhav", comment: "Convenient for work, decent property", rating: 4.1 }, { reviewer: "Harish Nair", comment: "Solid choice for budget conscious", rating: 3.9 }], owner: { name: "Owner 11", phone: "9000000011", email: "owner11@gmail.com" }, nearby: ["Railway Station","School"] },
  { id: 12, title: "3BHK Villa in Gangapur", city: "Nashik", area: "Gangapur", propertyType: "Villa", size: "3BHK", furnished: "furnished", rent: 48000, amenities: ["Garden","Security"], photos: [], rating: 4.3, reviews: [{ reviewer: "Kavya Bhat", comment: "Lovely villa with modern finishes", rating: 4.4 }, { reviewer: "Sanjay Kulkarni", comment: "Good investment property", rating: 4.2 }, { reviewer: "Priya Rao", comment: "Well maintained, friendly owner", rating: 4.3 }], owner: { name: "Owner 12", phone: "9000000012", email: "owner12@gmail.com" }, nearby: ["Hospital","Mall"] },
  { id: 13, title: "1BHK Flat in Panchavati", city: "Nashik", area: "Panchavati", propertyType: "Flat", size: "1BHK", furnished: "semifurnished", rent: 16000, amenities: ["Lift"], photos: [], rating: 3.8, reviews: [{ reviewer: "Rahul Agarwal", comment: "Budget friendly, decent location", rating: 3.7 }, { reviewer: "Deepa Singh", comment: "Near temple, peaceful area", rating: 3.9 }, { reviewer: "Nitin Patel", comment: "Good for starters", rating: 3.8 }], owner: { name: "Owner 13", phone: "9000000013", email: "owner13@gmail.com" }, nearby: ["Temple","School"] },
  { id: 14, title: "4BHK Penthouse in Indira Nagar", city: "Nashik", area: "Indira Nagar", propertyType: "Penthouse", size: "4BHK", furnished: "furnished", rent: 75000, amenities: ["Gym","Swimming Pool"], photos: [], rating: 4.7, reviews: [{ reviewer: "Devendra Sharma", comment: "Excellent penthouse with great views", rating: 4.8 }, { reviewer: "Swati Deshmukh", comment: "Premium living experience", rating: 4.7 }, { reviewer: "Anil Goyal", comment: "Worth every penny", rating: 4.6 }], owner: { name: "Owner 14", phone: "9000000014", email: "owner14@gmail.com" }, nearby: ["Mall","Hospital"] },
  { id: 15, title: "3BHK Bungalow in College Road", city: "Nashik", area: "College Road", propertyType: "Bungalow", size: "3BHK", furnished: "unfurnished", rent: 45000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: [{ reviewer: "Neelam Joshi", comment: "Beautiful bungalow on quiet road", rating: 4.3 }, { reviewer: "Prakash Sharma", comment: "Great for families", rating: 4.2 }, { reviewer: "Rita Verma", comment: "Good property value", rating: 4.1 }], owner: { name: "Owner 15", phone: "9000000015", email: "owner15@gmail.com" }, nearby: ["School","Hospital"] },

  // Continue similar variation till 50

  { id: 16, title: "2BHK Flat in Dharampeth", city: "Nagpur", area: "Dharampeth", propertyType: "Flat", size: "2BHK", furnished: "semifurnished", rent: 30000, amenities: ["Lift","Parking"], photos: [], rating: 4.1, reviews: [{ reviewer: "Aaryan Singh", comment: "Central location, modern flat", rating: 4.2 }, { reviewer: "Monica Dixit", comment: "Good neighborhood, peaceful", rating: 4 }, { reviewer: "Saurabh Desai", comment: "Best property in this price range", rating: 4.1 }], owner: { name: "Owner 16", phone: "9000000016", email: "owner16@gmail.com" }, nearby: ["Hospital","School"] },
  { id: 17, title: "3BHK Villa in Wardha Road", city: "Nagpur", area: "Wardha Road", propertyType: "Villa", size: "3BHK", furnished: "furnished", rent: 52000, amenities: ["Garden","Security"], photos: [], rating: 4.4, reviews: [{ reviewer: "Gita Chouhan", comment: "Spacious villa with excellent interiors", rating: 4.5 }, { reviewer: "Rajat Mishra", comment: "Great for joint family", rating: 4.4 }, { reviewer: "Ananya Jain", comment: "Perfect location near airport", rating: 4.3 }], owner: { name: "Owner 17", phone: "9000000017", email: "owner17@gmail.com" }, nearby: ["Airport","Mall"] },
  { id: 18, title: "1BHK Flat in Sitabuldi", city: "Nagpur", area: "Sitabuldi", propertyType: "Flat", size: "1BHK", furnished: "unfurnished", rent: 17000, amenities: ["Lift"], photos: [], rating: 3.9, reviews: [{ reviewer: "Ethan Moore", comment: "Compact and affordable", rating: 3.9 }, { reviewer: "Sheela Menon", comment: "Good basic amenities", rating: 3.9 }, { reviewer: "Raj Krishnan", comment: "Decent for the price", rating: 3.9 }], owner: { name: "Owner 18", phone: "9000000018", email: "owner18@gmail.com" }, nearby: ["Metro Station"] },
  { id: 19, title: "4BHK Penthouse in Pratap Nagar", city: "Nagpur", area: "Pratap Nagar", propertyType: "Penthouse", size: "4BHK", furnished: "furnished", rent: 80000, amenities: ["Swimming Pool","Gym"], photos: [], rating: 4.8, reviews: [{ reviewer: "Samir Sinha", comment: "Ultra-luxury penthouse, impeccable", rating: 4.9 }, { reviewer: "Tina Reddy", comment: "Perfect for executives", rating: 4.8 }, { reviewer: "Harsh Yadav", comment: "Top-tier property", rating: 4.7 }], owner: { name: "Owner 19", phone: "9000000019", email: "owner19@gmail.com" }, nearby: ["Mall","Hospital"] },
  { id: 20, title: "3BHK Bungalow in Manish Nagar", city: "Nagpur", area: "Manish Nagar", propertyType: "Bungalow", size: "3BHK", furnished: "semifurnished", rent: 47000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: [{ reviewer: "Veena Sharma", comment: "Green surroundings, peaceful area", rating: 4.3 }, { reviewer: "Sameer Gupta", comment: "Well-designed property", rating: 4.2 }, { reviewer: "Sunita Agarwal", comment: "Good value for money", rating: 4.1 }], owner: { name: "Owner 20", phone: "9000000020", email: "owner20@gmail.com" }, nearby: ["School","Hospital"] },

  // Final set for Aurangabad

  { id: 21, title: "2BHK Flat in CIDCO", city: "Aurangabad", area: "CIDCO", propertyType: "Flat", size: "2BHK", furnished: "unfurnished", rent: 26000, amenities: ["Lift","Parking"], photos: [], rating: 4.0, reviews: [{ reviewer: "Anmol Singh", comment: "Well-planned community, good amenities", rating: 4.1 }, { reviewer: "Priyanka Rao", comment: "Spacious and clean", rating: 4 }, { reviewer: "Aryan Verma", comment: "Good investment area", rating: 3.9 }], owner: { name: "Owner 21", phone: "9000000021", email: "owner21@gmail.com" }, nearby: ["School","Hospital"] },
  { id: 22, title: "3BHK Villa in Garkheda", city: "Aurangabad", area: "Garkheda", propertyType: "Villa", size: "3BHK", furnished: "furnished", rent: 46000, amenities: ["Garden","Security"], photos: [], rating: 4.3, reviews: [{ reviewer: "Deepak Yadav", comment: "Beautiful villa with modern design", rating: 4.4 }, { reviewer: "Pooja Saxena", comment: "Excellent security and privacy", rating: 4.3 }, { reviewer: "Rohit Jadhav", comment: "Great for peacful living", rating: 4.2 }], owner: { name: "Owner 22", phone: "9000000022", email: "owner22@gmail.com" }, nearby: ["Mall","School"] },
  { id: 23, title: "1BHK Flat in Osmanpura", city: "Aurangabad", area: "Osmanpura", propertyType: "Flat", size: "1BHK", furnished: "semifurnished", rent: 15000, amenities: ["Lift"], photos: [], rating: 3.7, reviews: [{ reviewer: "Malik Hassan", comment: "Budget-friendly option", rating: 3.8 }, { reviewer: "Fatima Khan", comment: "Basic but clean", rating: 3.7 }, { reviewer: "Ahmed Ali", comment: "Decent for budget", rating: 3.6 }], owner: { name: "Owner 23", phone: "9000000023", email: "owner23@gmail.com" }, nearby: ["Hospital"] },
  { id: 24, title: "4BHK Penthouse in Jalna Road", city: "Aurangabad", area: "Jalna Road", propertyType: "Penthouse", size: "4BHK", furnished: "furnished", rent: 70000, amenities: ["Swimming Pool","Gym"], photos: [], rating: 4.7, reviews: [{ reviewer: "Rajesh Iyer", comment: "Premium penthouse with best views", rating: 4.8 }, { reviewer: "Sunita Sharma", comment: "Excellent for entertainment", rating: 4.7 }, { reviewer: "Vikram Desai", comment: "Outstanding property quality", rating: 4.6 }], owner: { name: "Owner 24", phone: "9000000024", email: "owner24@gmail.com" }, nearby: ["Mall","Airport"] },
  { id: 25, title: "3BHK Bungalow in Satara", city: "Aurangabad", area: "Satara", propertyType: "Bungalow", size: "3BHK", furnished: "unfurnished", rent: 42000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: [{ reviewer: "Naveen Kumar", comment: "Spacious bungalow, great surroundings", rating: 4.3 }, { reviewer: "Anjana Nair", comment: "Perfect for large families", rating: 4.2 }, { reviewer: "Sanjay Patel", comment: "Good property value", rating: 4.1 }], owner: { name: "Owner 25", phone: "9000000025", email: "owner25@gmail.com" }, nearby: ["School","Hospital"] },

  // Pune - Additional properties
  { id: 26, title: "2BHK Flat in Viman Nagar", city: "Pune", area: "Viman Nagar", propertyType: "Flat", size: "2BHK", furnished: "furnished", rent: 38000, amenities: ["Lift","Parking","Gym"], photos: [], rating: 4.3, reviews: [{ reviewer: "Lakshmi Devi", comment: "Near airport, modern amenities", rating: 4.4 }, { reviewer: "Arjun Reddy", comment: "Great location, well maintained", rating: 4.3 }, { reviewer: "Sneha Nair", comment: "Perfect for professionals", rating: 4.2 }], owner: { name: "Owner 26", phone: "9000000026", email: "owner26@gmail.com" }, nearby: ["Airport","School"] },
  { id: 27, title: "3BHK Villa in Kalyani Nagar", city: "Pune", area: "Kalyani Nagar", propertyType: "Villa", size: "3BHK", furnished: "semifurnished", rent: 58000, amenities: ["Garden","Parking","Security"], photos: [], rating: 4.5, reviews: [{ reviewer: "Rajeev Sharma", comment: "Elegant villa in peaceful area", rating: 4.6 }, { reviewer: "Divya Vaid", comment: "Great for families", rating: 4.5 }, { reviewer: "Hardik Patel", comment: "Excellent property quality", rating: 4.4 }], owner: { name: "Owner 27", phone: "9000000027", email: "owner27@gmail.com" }, nearby: ["Restaurant","Hospital"] },
  { id: 28, title: "1BHK Flat in Shivajinagar", city: "Pune", area: "Shivajinagar", propertyType: "Flat", size: "1BHK", furnished: "unfurnished", rent: 19000, amenities: ["Lift","Security"], photos: [], rating: 3.8, reviews: [{ reviewer: "Ravi Kumar", comment: "Good connectivity, central location", rating: 3.9 }, { reviewer: "Neha Singh", comment: "Affordable and convenient", rating: 3.8 }, { reviewer: "Sanjay Bhat", comment: "Basic but functional", rating: 3.7 }], owner: { name: "Owner 28", phone: "9000000028", email: "owner28@gmail.com" }, nearby: ["Market","School"] },
  { id: 29, title: "4BHK Penthouse in Baner", city: "Pune", area: "Baner", propertyType: "Penthouse", size: "4BHK", furnished: "furnished", rent: 88000, amenities: ["Swimming Pool","Gym","Garden"], photos: [], rating: 4.9, reviews: [{ reviewer: "Hemant Iyer", comment: "Stunning penthouse, world-class", rating: 5 }, { reviewer: "Nisha Deshmukh", comment: "Perfect luxury living", rating: 4.9 }, { reviewer: "Ashish Nair", comment: "Exceptional in every way", rating: 4.8 }], owner: { name: "Owner 29", phone: "9000000029", email: "owner29@gmail.com" }, nearby: ["Mall","Hospital"] },
  { id: 30, title: "3BHK Bungalow in Pimple Saudagar", city: "Pune", area: "Pimple Saudagar", propertyType: "Bungalow", size: "3BHK", furnished: "semifurnished", rent: 52000, amenities: ["Garden","Parking","Lift"], photos: [], rating: 4.2, reviews: [{ reviewer: "Meera Chopra", comment: "Beautiful bungalow in nice locality", rating: 4.3 }, { reviewer: "Rajesh Singh", comment: "Family-friendly area", rating: 4.2 }, { reviewer: "Aarav Malhotra", comment: "Good property and management", rating: 4.1 }], owner: { name: "Owner 30", phone: "9000000030", email: "owner30@gmail.com" }, nearby: ["School","Mall"] },

  // Mumbai - Additional properties
  { id: 31, title: "2BHK Flat in Worli", city: "Mumbai", area: "Worli", propertyType: "Flat", size: "2BHK", furnished: "furnished", rent: 45000, amenities: ["Lift","Parking","Gym"], photos: [], rating: 4.4, reviews: [{ reviewer: "Anupam Singh", comment: "Great sea view, premium location", rating: 4.5 }, { reviewer: "Disha Choudhury", comment: "Modern flat, excellent amenities", rating: 4.4 }, { reviewer: "Kaustubh Sharma", comment: "Best choice for young professionals", rating: 4.3 }], owner: { name: "Owner 31", phone: "9000000031", email: "owner31@gmail.com" }, nearby: ["Sea Face","Mall"] },
  { id: 32, title: "3BHK Villa in Juhu", city: "Mumbai", area: "Juhu", propertyType: "Villa", size: "3BHK", furnished: "semifurnished", rent: 70000, amenities: ["Garden","Security","Swimming Pool"], photos: [], rating: 4.6, reviews: [{ reviewer: "Meera Rao", comment: "Beachfront villa, absolutely stunning", rating: 4.7 }, { reviewer: "Aryan Bhat", comment: "Premium property with great vibe", rating: 4.6 }, { reviewer: "Priya Malik", comment: "Perfect for celebrity lifestyle", rating: 4.5 }], owner: { name: "Owner 32", phone: "9000000032", email: "owner32@gmail.com" }, nearby: ["Beach","Restaurant"] },
  { id: 33, title: "1BHK Flat in Thane", city: "Mumbai", area: "Thane", propertyType: "Flat", size: "1BHK", furnished: "unfurnished", rent: 20000, amenities: ["Lift","Security"], photos: [], rating: 3.9, reviews: [{ reviewer: "Vikram Menon", comment: "Affordable, near lake", rating: 4 }, { reviewer: "Shreya Desai", comment: "Good for budget traveler", rating: 3.9 }, { reviewer: "Nikhil Agarwal", comment: "Decent property value", rating: 3.8 }], owner: { name: "Owner 33", phone: "9000000033", email: "owner33@gmail.com" }, nearby: ["Lake","School"] },
  { id: 34, title: "4BHK Penthouse in Mumbai Central", city: "Mumbai", area: "Mumbai Central", propertyType: "Penthouse", size: "4BHK", furnished: "furnished", rent: 100000, amenities: ["Swimming Pool","Gym","Spa"], photos: [], rating: 4.8, reviews: [{ reviewer: "Shashank Rao", comment: "Ultimate luxury penthouse, unmatched", rating: 4.9 }, { reviewer: "Rekha Sharma", comment: "Perfect for power couples", rating: 4.8 }, { reviewer: "Aditya Singh", comment: "Five-star living experience", rating: 4.7 }], owner: { name: "Owner 34", phone: "9000000034", email: "owner34@gmail.com" }, nearby: ["Downtown","Airport"] },
  { id: 35, title: "3BHK Bungalow in Navi Mumbai", city: "Mumbai", area: "Navi Mumbai", propertyType: "Bungalow", size: "3BHK", furnished: "semifurnished", rent: 55000, amenities: ["Garden","Parking","Lift"], photos: [], rating: 4.3, reviews: [{ reviewer: "Sunita Yadav", comment: "Planned community, modern amenities", rating: 4.4 }, { reviewer: "Sameer Desai", comment: "Great investment opportunity", rating: 4.3 }, { reviewer: "Geeta Nair", comment: "Good for families with kids", rating: 4.2 }], owner: { name: "Owner 35", phone: "9000000035", email: "owner35@gmail.com" }, nearby: ["Metro Station","School"] },

  // Nashik - Additional properties
  { id: 36, title: "2BHK Flat in Satpur", city: "Nashik", area: "Satpur", propertyType: "Flat", size: "2BHK", furnished: "unfurnished", rent: 27000, amenities: ["Lift","Parking"], photos: [], rating: 4.1, reviews: [{ reviewer: "Varun Sharma", comment: "Growing area, good for investment", rating: 4.2 }, { reviewer: "Sapna Jain", comment: "Modern development, decent property", rating: 4.1 }, { reviewer: "Nitin Deshmukh", comment: "Good value, peaceful location", rating: 4 }], owner: { name: "Owner 36", phone: "9000000036", email: "owner36@gmail.com" }, nearby: ["School","Hospital"] },
  { id: 37, title: "3BHK Villa in Manmad", city: "Nashik", area: "Manmad", propertyType: "Villa", size: "3BHK", furnished: "furnished", rent: 50000, amenities: ["Garden","Security"], photos: [], rating: 4.4, reviews: [{ reviewer: "Isha Verma", comment: "Beautiful villa near railway hub", rating: 4.5 }, { reviewer: "Dhruv Patel", comment: "Great connectivity, nice property", rating: 4.4 }, { reviewer: "Anjali Singh", comment: "Excellent for business area", rating: 4.3 }], owner: { name: "Owner 37", phone: "9000000037", email: "owner37@gmail.com" }, nearby: ["Railway Station","Mall"] },
  { id: 38, title: "1BHK Flat in Deolali", city: "Nashik", area: "Deolali", propertyType: "Flat", size: "1BHK", furnished: "semifurnished", rent: 15500, amenities: ["Lift"], photos: [], rating: 3.7, reviews: [{ reviewer: "Sukhvinder Singh", comment: "Cantonment area, safe location", rating: 3.8 }, { reviewer: "Rita Pillai", comment: "Good for single occupants", rating: 3.7 }, { reviewer: "Mahendra Kumar", comment: "Basic amenities, fair price", rating: 3.6 }], owner: { name: "Owner 38", phone: "9000000038", email: "owner38@gmail.com" }, nearby: ["Cantonment","School"] },
  { id: 39, title: "4BHK Penthouse in Nashik Central", city: "Nashik", area: "Nashik Central", propertyType: "Penthouse", size: "4BHK", furnished: "furnished", rent: 78000, amenities: ["Gym","Swimming Pool","Garden"], photos: [], rating: 4.7, reviews: [{ reviewer: "Vedavati Rao", comment: "Premium penthouse in city center", rating: 4.8 }, { reviewer: "Chetan Sharma", comment: "Excellent for elite living", rating: 4.7 }, { reviewer: "Pooja Bhat", comment: "Outstanding property features", rating: 4.6 }], owner: { name: "Owner 39", phone: "9000000039", email: "owner39@gmail.com" }, nearby: ["Market","Hospital"] },
  { id: 40, title: "3BHK Bungalow in Umanabad", city: "Nashik", area: "Umanabad", propertyType: "Bungalow", size: "3BHK", furnished: "semifurnished", rent: 48000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: [{ reviewer: "Mohan Desai", comment: "Quiet locality, spacious bungalow", rating: 4.3 }, { reviewer: "Shruti Nair", comment: "Good for families, green area", rating: 4.2 }, { reviewer: "Bhavesh Reddy", comment: "Fair pricing and maintenance", rating: 4.1 }], owner: { name: "Owner 40", phone: "9000000040", email: "owner40@gmail.com" }, nearby: ["School","Hospital"] },

  // Nagpur - Additional properties
  { id: 41, title: "2BHK Flat in Ramdaspeth", city: "Nagpur", area: "Ramdaspeth", propertyType: "Flat", size: "2BHK", furnished: "furnished", rent: 31000, amenities: ["Lift","Parking","Gym"], photos: [], rating: 4.2, reviews: [{ reviewer: "Yamini Sharma", comment: "Prime location, modern flat", rating: 4.3 }, { reviewer: "Sunil Rao", comment: "City market area, convenient", rating: 4.2 }, { reviewer: "Anjali Bhat", comment: "Good connectivity and amenities", rating: 4.1 }], owner: { name: "Owner 41", phone: "9000000041", email: "owner41@gmail.com" }, nearby: ["Market","School"] },
  { id: 42, title: "3BHK Villa in Nagpur North", city: "Nagpur", area: "Nagpur North", propertyType: "Villa", size: "3BHK", furnished: "semifurnished", rent: 54000, amenities: ["Garden","Security","Lift"], photos: [], rating: 4.5, reviews: [{ reviewer: "Rajesh Kumar", comment: "Near golf course, premium locality", rating: 4.6 }, { reviewer: "Priya Menon", comment: "Spacious villa with modern design", rating: 4.5 }, { reviewer: "Ashish Nair", comment: "Excellent neighborhood quality", rating: 4.4 }], owner: { name: "Owner 42", phone: "9000000042", email: "owner42@gmail.com" }, nearby: ["Golf Course","Hospital"] },
  { id: 43, title: "1BHK Flat in Itwari", city: "Nagpur", area: "Itwari", propertyType: "Flat", size: "1BHK", furnished: "unfurnished", rent: 18000, amenities: ["Lift","Security"], photos: [], rating: 3.8, reviews: [{ reviewer: "Rohit Singh", comment: "Budget option, decent property", rating: 3.9 }, { reviewer: "Divya Rao", comment: "Good for students", rating: 3.8 }, { reviewer: "Karan Jain", comment: "Fair price for location", rating: 3.7 }], owner: { name: "Owner 43", phone: "9000000043", email: "owner43@gmail.com" }, nearby: ["School","Mall"] },
  { id: 44, title: "4BHK Penthouse in South Nagpur", city: "Nagpur", area: "South Nagpur", propertyType: "Penthouse", size: "4BHK", furnished: "furnished", rent: 82000, amenities: ["Swimming Pool","Gym","Spa"], photos: [], rating: 4.8, reviews: [{ reviewer: "Saurav Iyer", comment: "Ultra-luxury penthouse experience", rating: 4.9 }, { reviewer: "Neelima Sharma", comment: "Perfect for high-profile living", rating: 4.8 }, { reviewer: "Arjun Desai", comment: "Best penthouse in Nagpur", rating: 4.7 }], owner: { name: "Owner 44", phone: "9000000044", email: "owner44@gmail.com" }, nearby: ["Race Course","Restaurant"] },
  { id: 45, title: "3BHK Bungalow in Ameerpeth", city: "Nagpur", area: "Ameerpeth", propertyType: "Bungalow", size: "3BHK", furnished: "semifurnished", rent: 49000, amenities: ["Garden","Parking"], photos: [], rating: 4.2, reviews: [{ reviewer: "Vinita Shah", comment: "Beautiful bungalow in heritage area", rating: 4.3 }, { reviewer: "Mahesh Nair", comment: "Great for traditional living", rating: 4.2 }, { reviewer: "Ravi Rao", comment: "Good property management", rating: 4.1 }], owner: { name: "Owner 45", phone: "9000000045", email: "owner45@gmail.com" }, nearby: ["School","Hospital"] },

  // Aurangabad - Additional properties
  { id: 46, title: "2BHK Flat in Aurangabad East", city: "Aurangabad", area: "Aurangabad East", propertyType: "Flat", size: "2BHK", furnished: "unfurnished", rent: 27000, amenities: ["Lift","Parking"], photos: [], rating: 4.1, reviews: [{ reviewer: "Fatima Shaikh", comment: "Near historical monuments, great area", rating: 4.2 }, { reviewer: "Ali Khan", comment: "Good locality with tourist advantage", rating: 4.1 }, { reviewer: "Zainab Sheikh", comment: "Well connected, fair pricing", rating: 4 }], owner: { name: "Owner 46", phone: "9000000046", email: "owner46@gmail.com" }, nearby: ["Bibi Ka Maqbara","School"] },
  { id: 47, title: "3BHK Villa in Paithan Gate", city: "Aurangabad", area: "Paithan Gate", propertyType: "Villa", size: "3BHK", furnished: "furnished", rent: 47000, amenities: ["Garden","Security"], photos: [], rating: 4.3, reviews: [{ reviewer: "Syed Ahmed", comment: "Historical area villa with character", rating: 4.4 }, { reviewer: "Ayesha Patel", comment: "Spiritual location, peaceful vibes", rating: 4.3 }, { reviewer: "Mohammed Hussain", comment: "Great for culture enthusiasts", rating: 4.2 }], owner: { name: "Owner 47", phone: "9000000047", email: "owner47@gmail.com" }, nearby: ["Temple","Hospital"] },
  { id: 48, title: "1BHK Flat in Chikhalwadi", city: "Aurangabad", area: "Chikhalwadi", propertyType: "Flat", size: "1BHK", furnished: "semifurnished", rent: 16000, amenities: ["Lift"], photos: [], rating: 3.8, reviews: [{ reviewer: "Hassan Ahmed", comment: "Affordable, basic amenities", rating: 3.8 }, { reviewer: "Zara Malik", comment: "Good for budget stay", rating: 3.8 }, { reviewer: "Ibrahim Khan", comment: "Fair property for price", rating: 3.8 }], owner: { name: "Owner 48", phone: "9000000048", email: "owner48@gmail.com" }, nearby: ["School"] },
  { id: 49, title: "4BHK Penthouse in Aurangabad West", city: "Aurangabad", area: "Aurangabad West", propertyType: "Penthouse", size: "4BHK", furnished: "furnished", rent: 72000, amenities: ["Swimming Pool","Gym"], photos: [], rating: 4.7, reviews: [{ reviewer: "Rajesh Khan", comment: "Modern penthouse with luxury finish", rating: 4.8 }, { reviewer: "Sneha Sharma", comment: "Excellent amenities and service", rating: 4.7 }, { reviewer: "Amir Patel", comment: "Premium living in Aurangabad", rating: 4.6 }], owner: { name: "Owner 49", phone: "9000000049", email: "owner49@gmail.com" }, nearby: ["Mall","Hospital"] },
  { id: 50, title: "3BHK Bungalow in Railway Station Road", city: "Aurangabad", area: "Railway Station Road", propertyType: "Bungalow", size: "3BHK", furnished: "semifurnished", rent: 44000, amenities: ["Garden","Parking","Security"], photos: [], rating: 4.2, reviews: [{ reviewer: "Khalid Ahmed", comment: "Convenient location near railway", rating: 4.3 }, { reviewer: "Nadia Khan", comment: "Well maintained bungalow", rating: 4.2 }, { reviewer: "Farhan Ali", comment: "Good for transit travelers", rating: 4.1 }], owner: { name: "Owner 50", phone: "9000000050", email: "owner50@gmail.com" }, nearby: ["Railway Station","School"] }

  
];

export default PROPERTIES;
